'use client';
export function WeavePattern({ className = '' }: { className?: string }) {
  return (
    <svg
      className={className}
      width='100%'
      height='100%'
      xmlns='http://www.w3.org/2000/svg'
      preserveAspectRatio='xMidYMid slice'
    >
      <defs>
        <pattern
          id='weave'
          x='0'
          y='0'
          width='80'
          height='80'
          patternUnits='userSpaceOnUse'
        >
          {/* 가로 직조 */}
          <rect
            x='0'
            y='0'
            width='40'
            height='20'
            fill='#8B7355'
            opacity='0.15'
          />
          <rect
            x='40'
            y='20'
            width='40'
            height='20'
            fill='#8B7355'
            opacity='0.15'
          />
          <rect
            x='0'
            y='40'
            width='40'
            height='20'
            fill='#6B8E23'
            opacity='0.12'
          />
          <rect
            x='40'
            y='60'
            width='40'
            height='20'
            fill='#6B8E23'
            opacity='0.12'
          />

          {/* 세로 직조 */}
          <rect
            x='0'
            y='20'
            width='20'
            height='40'
            fill='#D4A574'
            opacity='0.1'
          />
          <rect
            x='20'
            y='0'
            width='20'
            height='40'
            fill='#D4A574'
            opacity='0.1'
          />
          <rect
            x='40'
            y='20'
            width='20'
            height='40'
            fill='#B8860B'
            opacity='0.08'
          />
          <rect
            x='60'
            y='0'
            width='20'
            height='40'
            fill='#B8860B'
            opacity='0.08'
          />

          <rect
            x='0'
            y='60'
            width='20'
            height='40'
            fill='#D4A574'
            opacity='0.1'
          />
          <rect
            x='20'
            y='40'
            width='20'
            height='40'
            fill='#D4A574'
            opacity='0.1'
          />
          <rect
            x='40'
            y='60'
            width='20'
            height='40'
            fill='#B8860B'
            opacity='0.08'
          />
          <rect
            x='60'
            y='40'
            width='20'
            height='40'
            fill='#B8860B'
            opacity='0.08'
          />
        </pattern>
      </defs>
      <rect width='100%' height='100%' fill='url(#weave)' />
    </svg>
  );
}
